#!/usr/bin/env python3
"""
Cross-platform packaging script for the rbot AI Assistant.
Uses PyInstaller to bundle the application into a standalone binary
without distributing the source code.
"""
import os
import sys
import shutil
import subprocess
from pathlib import Path

def build_linux_packages(binary_path, dist_dir):
    """Builds .deb, .rpm, and .tar.gz packages for Debian, Fedora, Arch Linux, etc."""
    import shutil
    import tempfile
    import tarfile
    
    suffix = os.environ.get("RBOT_PKG_SUFFIX", "")
    
    # 1. Create Tar.gz archive (universal installer for Arch Linux, gentoo, etc.)
    tar_path = dist_dir / f"rbot-linux{suffix}.tar.gz"
    print(f"Creating universal Tar.gz archive at {tar_path}...")
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            shutil.copy(binary_path, tmp / "rbot")
            (tmp / "rbot").chmod(0o755)
            
            desktop_content = """[Desktop Entry]
Name=RBot
Comment=AI Desktop Assistant
Exec=rbot run
Icon=system-run
Terminal=false
Type=Application
Categories=Utility;Development;
"""
            with open(tmp / "rbot.desktop", "w", encoding="utf-8") as f:
                f.write(desktop_content)
                
            # Copy installers from scripts/prod/linux/
            root_dir = Path(__file__).parent.parent.resolve()
            shutil.copy(root_dir / "scripts" / "prod" / "linux" / "install.sh", tmp / "install.sh")
            (tmp / "install.sh").chmod(0o755)

            shutil.copy(root_dir / "scripts" / "prod" / "linux" / "uninstall.sh", tmp / "uninstall.sh")
            (tmp / "uninstall.sh").chmod(0o755)
            
            with tarfile.open(tar_path, "w:gz") as tar:
                tar.add(tmp / "rbot", arcname="rbot")
                tar.add(tmp / "rbot.desktop", arcname="rbot.desktop")
                tar.add(tmp / "install.sh", arcname="install.sh")
                tar.add(tmp / "uninstall.sh", arcname="uninstall.sh")
        print("  [OK] Tar.gz archive created successfully.")
    except Exception as e:
        print(f"  [ERROR] Failed to create Tar.gz archive: {e}")
        
    # 2. Create Debian/Ubuntu package (.deb)
    deb_path = dist_dir / f"rbot-linux{suffix}.deb"
    print(f"Creating Debian package at {deb_path}...")
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            control_dir = tmp / "DEBIAN"
            control_dir.mkdir(parents=True, exist_ok=True)
            
            bin_dir = tmp / "usr" / "bin"
            bin_dir.mkdir(parents=True, exist_ok=True)
            
            apps_dir = tmp / "usr" / "share" / "applications"
            apps_dir.mkdir(parents=True, exist_ok=True)
            
            shutil.copy(binary_path, bin_dir / "rbot")
            (bin_dir / "rbot").chmod(0o755)
            
            control_content = """Package: rbot
Version: 0.1.0
Section: utils
Priority: optional
Architecture: amd64
Maintainer: RBot Team <info@rbot.local>
Description: AI Desktop Assistant
 An agentic desktop AI assistant built in Python.
"""
            with open(control_dir / "control", "w", encoding="utf-8") as f:
                f.write(control_content)
                
            desktop_content = """[Desktop Entry]
Name=RBot
Comment=AI Desktop Assistant
Exec=rbot run
Icon=system-run
Terminal=false
Type=Application
Categories=Utility;Development;
"""
            with open(apps_dir / "rbot.desktop", "w", encoding="utf-8") as f:
                f.write(desktop_content)
                
            if shutil.which("dpkg-deb"):
                subprocess.run(["dpkg-deb", "--build", str(tmp), str(deb_path)], check=True, stdout=subprocess.DEVNULL)
                print("  [OK] Debian (.deb) package created successfully.")
            else:
                print("  [ERROR] dpkg-deb command not found. Skipping .deb creation.")
    except Exception as e:
        print(f"  [ERROR] Failed to create Debian package: {e}")
        
    # 3. Create RPM package (.rpm) using alien if available
    rpm_path = dist_dir / f"rbot-linux{suffix}.rpm"
    if deb_path.exists() and shutil.which("alien"):
        print(f"Converting Debian package to RPM using alien at {rpm_path}...")
        try:
            # Run alien with fakeroot or sudo depending on context
            alien_cmd = ["alien", "--to-rpm", "--scripts", str(deb_path)]
            if shutil.which("sudo") and os.getuid() != 0:
                alien_cmd = ["sudo"] + alien_cmd
            subprocess.run(alien_cmd, check=True)
            
            import glob
            rpms = glob.glob("rbot-*.rpm")
            if rpms:
                shutil.move(rpms[0], rpm_path)
                print("  [OK] RPM (.rpm) package created successfully.")
            else:
                print("  [ERROR] RPM file generated by alien could not be located.")
        except Exception as e:
            print(f"  [ERROR] Failed to convert .deb to .rpm: {e}")
    else:
        if not shutil.which("alien"):
            print("  [-] alien command not found. Skipping RPM conversion.")

def build_macos_packages(binary_path, dist_dir):
    """Builds a .tar.gz archive for macOS containing the binary, install.sh and uninstall.sh."""
    import shutil
    import tempfile
    import tarfile
    
    suffix = os.environ.get("RBOT_PKG_SUFFIX", "")
    tar_path = dist_dir / f"rbot-macos{suffix}.tar.gz"
    print(f"Creating universal macOS Tar.gz archive at {tar_path}...")
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            shutil.copy(binary_path, tmp / "rbot")
            (tmp / "rbot").chmod(0o755)
            
            # Copy installers from scripts/prod/macos/
            root_dir = Path(__file__).parent.parent.resolve()
            shutil.copy(root_dir / "scripts" / "prod" / "macos" / "install.sh", tmp / "install.sh")
            (tmp / "install.sh").chmod(0o755)

            shutil.copy(root_dir / "scripts" / "prod" / "macos" / "uninstall.sh", tmp / "uninstall.sh")
            (tmp / "uninstall.sh").chmod(0o755)
            
            with tarfile.open(tar_path, "w:gz") as tar:
                tar.add(tmp / "rbot", arcname="rbot")
                tar.add(tmp / "install.sh", arcname="install.sh")
                tar.add(tmp / "uninstall.sh", arcname="uninstall.sh")
        print("  [OK] macOS Tar.gz archive created successfully.")
    except Exception as e:
        print(f"  [ERROR] Failed to create macOS package: {e}")

def build_windows_packages(binary_path, dist_dir):
    """Builds a .zip archive for Windows containing the binary, install.bat and uninstall.bat."""
    import zipfile
    
    suffix = os.environ.get("RBOT_PKG_SUFFIX", "")
    zip_path = dist_dir / f"rbot-windows{suffix}.zip"
    print(f"Creating Windows ZIP archive at {zip_path}...")
    try:
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
            zipf.write(binary_path, arcname="rbot.exe")
            
            root_dir = Path(__file__).parent.parent.resolve()
            install_bat_path = root_dir / "scripts" / "prod" / "windows" / "install.bat"
            uninstall_bat_path = root_dir / "scripts" / "prod" / "windows" / "uninstall.bat"
            
            zipf.write(install_bat_path, arcname="install.bat")
            zipf.write(uninstall_bat_path, arcname="uninstall.bat")
            
        print("  [OK] Windows ZIP archive created successfully.")
    except Exception as e:
        print(f"  [ERROR] Failed to create Windows package: {e}")

def main():
    print("=========================================")
    print("      rbot Standalone Packaging Script   ")
    print("=========================================")

    root = Path(__file__).parent.parent.resolve()
    os.chdir(root)

    # 1. Ensure PyInstaller is installed
    try:
        import PyInstaller
    except ImportError:
        print("PyInstaller is not installed in the current environment.")
        print("Installing PyInstaller...")
        subprocess.run([sys.executable, "-m", "pip", "install", "pyinstaller"], check=True)

    # 2. Determine separator for --add-data
    # Windows uses semicolon (;), Unix uses colon (:)
    sep = ";" if sys.platform == "win32" else ":"

    # 3. Define the PyInstaller arguments
    entry_point = "cli/main.py"
    
    add_data_ui = f"interfaces/web_ui{sep}interfaces/web_ui"
    
    # Bundle individual configuration files and manifests, excluding local/temp directories like chromium-panel-rbot
    yaml_files = ["app.yml", "llm.yml", "memory.yml", "platforms.yml", "security.yml", "tools.yml", "voice.yml"]
    add_data_args = [f"--add-data={add_data_ui}"]
    for yml in yaml_files:
        add_data_args.append(f"--add-data=configs/{yml}{sep}configs")
    add_data_args.append(f"--add-data=configs/manifests{sep}configs/manifests")

    args = [
        entry_point,
        "--name=rbot",
        "--paths=.",
        "--onefile",  # Package into a single executable binary
    ] + add_data_args + [
        "--clean",
        "--noconfirm",
        "--console",
    ]

    print(f"Running PyInstaller with arguments: {args}")
    
    try:
        import PyInstaller.__main__
        PyInstaller.__main__.run(args)
        print("\n=========================================")
        print("Packaging complete!")
        
        # Locate the compiled binary
        bin_ext = ".exe" if sys.platform == "win32" else ""
        binary_path = root / "dist" / f"rbot{bin_ext}"
        if binary_path.exists():
            print(f"Standalone executable binary created at: {binary_path}")
            print("You can distribute this binary directly without the source code.")
            
            if sys.platform == "linux":
                build_linux_packages(binary_path, root / "dist")
            elif sys.platform == "darwin":
                build_macos_packages(binary_path, root / "dist")
            elif sys.platform == "win32":
                build_windows_packages(binary_path, root / "dist")
                
        print("=========================================")
    except Exception as e:
        print(f"Error packaging application: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
